# ML Zoomcamp 2026 — Homework 1

## Q1. Pandas Version

Check the installed Pandas version.

In [1]:
import pandas as pd

pd.__version__

'2.3.3'

## Q2. Records count

How many records are in the dataset?

In [2]:
import pandas as pd 
df = pd.read_csv("car_fuel_efficiency_2026.csv")

In [4]:
len(df)

10000

## Q3. Fuel types 

How many fuel types are presented in the dataset?

In [5]:
df.columns

Index(['model_year', 'origin', 'fuel_type', 'drivetrain', 'num_doors',
       'engine_displacement', 'num_cylinders', 'horsepower', 'vehicle_weight',
       'acceleration', 'fuel_efficiency_mpg'],
      dtype='object')

In [6]:
df['fuel_type'].nunique()

3

## Q4. Missing values

How many columns in the dataset have missing values?

In [7]:
df.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

In [8]:
(df.isnull().sum() > 0).sum()

np.int64(2)

## Q5. Max fuel efficiency
What's the maximum fuel efficiency of cars from Asia?

In [9]:
df['origin'].unique()

array(['Europe', 'Asia', 'USA'], dtype=object)

In [10]:
df[df['origin'] == 'Asia']['fuel_efficiency_mpg'].max()

np.float64(41.2)

## Q6. Median value of horsepower

Find the median value of the horsepower column in the dataset.


In [11]:
df['horsepower'].median()

np.float64(254.0)

Next, calculate the most frequent value of the same horsepower column.


In [12]:
df['horsepower'].mode()

0    252.0
Name: horsepower, dtype: float64

Use the fillna method to fill the missing values in the horsepower column with the most frequent value from the previous step.


In [14]:
df['horsepower'] = df['horsepower'].fillna(252.0)
df['horsepower'].isnull().sum()

np.int64(0)

Now, calculate the median value of horsepower once again.

Has it changed?
> Yes, it changed from 254.0 to 252.0

In [15]:
df['horsepower'].median()

np.float64(252.0)

## Q7. Sum of weights
1. Select all the cars from Asia
2. Select only columns vehicle_weight and model_year
3. Select the first 7 values
4. Get the underlying NumPy array. Let's call it X.

In [16]:
X = df[df['origin'] == 'Asia'][['vehicle_weight', 'model_year']].head(7).to_numpy()

X

array([[4240, 1996],
       [4310, 1992],
       [4230, 1997],
       [4420, 1978],
       [3950, 2007],
       [4750, 2021],
       [4450, 2019]])

5. Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.

In [17]:
XTX = X.T @ X
XTX

array([[131950500,  60750580],
       [ 60750580,  28041424]])

6. Invert XTX.

In [19]:
import numpy as np
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 2.96830537e-06, -6.43071025e-06],
       [-6.43071025e-06,  1.39675281e-05]])

7. Create an array y with values [1100, 1300, 800, 900, 1000, 1100, 1200].
Multiply the inverse of XTX with the transpose of X, and then multiply the result by y.

In [20]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
y

array([1100, 1300,  800,  900, 1000, 1100, 1200])

8. Calculate the result w.

In [21]:
w = XTX_inv @ X.T @ y
w

array([0.13644777, 0.2327492 ])

9. What's the sum of all the elements of the result?

In [22]:
w.sum()

np.float64(0.36919696904925486)